cp loop_zlm_etapi.cfg EtaPi_fit/bin_0
cp loop_zlm_etapi.cfg EtaPi_fit/bin_1
cp loop_zlm_etapi.cfg EtaPi_fit/bin_2
cp loop_zlm_etapi.cfg EtaPi_fit/bin_3
cp loop_zlm_etapi.cfg EtaPi_fit/bin_4
cp loop_zlm_etapi.cfg EtaPi_fit/bin_5
cp loop_zlm_etapi.cfg EtaPi_fit/bin_6
cp loop_zlm_etapi.cfg EtaPi_fit/bin_7
cp loop_zlm_etapi.cfg EtaPi_fit/bin_8
cp loop_zlm_etapi.cfg EtaPi_fit/bin_9
cp loop_zlm_etapi.cfg EtaPi_fit/bin_10
cp loop_zlm_etapi.cfg EtaPi_fit/bin_11
cp loop_zlm_etapi.cfg EtaPi_fit/bin_12
cp loop_zlm_etapi.cfg EtaPi_fit/bin_13
cp loop_zlm_etapi.cfg EtaPi_fit/bin_14
cp loop_zlm_etapi.cfg EtaPi_fit/bin_15
cp loop_zlm_etapi.cfg EtaPi_fit/bin_16
cp loop_zlm_etapi.cfg EtaPi_fit/bin_17
cp loop_zlm_etapi.cfg EtaPi_fit/bin_18
cp loop_zlm_etapi.cfg EtaPi_fit/bin_19
cp loop_zlm_etapi.cfg EtaPi_fit/bin_20
cp loop_zlm_etapi.cfg EtaPi_fit/bin_21
cp loop_zlm_etapi.cfg EtaPi_fit/bin_22
cp loop_zlm_etapi.cfg EtaPi_fit/bin_23
cp loop_zlm_etapi.cfg EtaPi_fit/bin_24
cp loop_zlm_etapi.cfg EtaPi_fit/bin_25
cp loop_zlm_etapi.cfg EtaPi_fit/bin_26
cp loop_zlm_etapi.cfg EtaPi_fit/bin_27
cp loop_zlm_etapi.cfg EtaPi_fit/bin_28
cp loop_zlm_etapi.cfg EtaPi_fit/bin_29
cp loop_zlm_etapi.cfg EtaPi_fit/bin_30
cp loop_zlm_etapi.cfg EtaPi_fit/bin_31
cp loop_zlm_etapi.cfg EtaPi_fit/bin_32
cp loop_zlm_etapi.cfg EtaPi_fit/bin_33
cp loop_zlm_etapi.cfg EtaPi_fit/bin_34
cp loop_zlm_etapi.cfg EtaPi_fit/bin_35
cp loop_zlm_etapi.cfg EtaPi_fit/bin_36
cp loop_zlm_etapi.cfg EtaPi_fit/bin_37
cp loop_zlm_etapi.cfg EtaPi_fit/bin_38
cp loop_zlm_etapi.cfg EtaPi_fit/bin_39
cp loop_zlm_etapi.cfg EtaPi_fit/bin_40
cp loop_zlm_etapi.cfg EtaPi_fit/bin_41
cp loop_zlm_etapi.cfg EtaPi_fit/bin_42
cp loop_zlm_etapi.cfg EtaPi_fit/bin_43
cp loop_zlm_etapi.cfg EtaPi_fit/bin_44
cp loop_zlm_etapi.cfg EtaPi_fit/bin_45
cp loop_zlm_etapi.cfg EtaPi_fit/bin_46
cp loop_zlm_etapi.cfg EtaPi_fit/bin_47
cp loop_zlm_etapi.cfg EtaPi_fit/bin_48
cp loop_zlm_etapi.cfg EtaPi_fit/bin_49
cp loop_zlm_etapi.cfg EtaPi_fit/bin_50
cp loop_zlm_etapi.cfg EtaPi_fit/bin_51
cp loop_zlm_etapi.cfg EtaPi_fit/bin_52
cp loop_zlm_etapi.cfg EtaPi_fit/bin_53
cp loop_zlm_etapi.cfg EtaPi_fit/bin_54
cp loop_zlm_etapi.cfg EtaPi_fit/bin_55
cp loop_zlm_etapi.cfg EtaPi_fit/bin_56
cp loop_zlm_etapi.cfg EtaPi_fit/bin_57
cp loop_zlm_etapi.cfg EtaPi_fit/bin_58
cp loop_zlm_etapi.cfg EtaPi_fit/bin_59
cp loop_zlm_etapi.cfg EtaPi_fit/bin_60
cp loop_zlm_etapi.cfg EtaPi_fit/bin_61
cp loop_zlm_etapi.cfg EtaPi_fit/bin_62
cp loop_zlm_etapi.cfg EtaPi_fit/bin_63
cp loop_zlm_etapi.cfg EtaPi_fit/bin_64
cp loop_zlm_etapi.cfg EtaPi_fit/bin_65
